# Generated by Django 2.0.2 on 2018-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=100)),
                ('wind_speed', models.CharField(max_length=100)),
                ('hunidity', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=100)),
            ],
        ),
    ]
