# Generated by Django 2.0.3 on 2018-11-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20181115_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditions',
            old_name='humidity',
            new_name='hunidity',
        ),
    ]
