# Generated by Django 2.0.3 on 2018-11-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20181115_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditions',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='hunidity',
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='wind_speed',
        ),
    ]
