# Generated by Django 2.0.3 on 2018-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20181115_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='city_code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditions',
            name='humidity',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditions',
            name='temperature',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditions',
            name='wind_speed',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
