# Generated by Django 2.0.3 on 2018-11-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20181125_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditions',
            old_name='city_code',
            new_name='temp',
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='temperature',
        ),
    ]
