# Generated by Django 2.0.3 on 2018-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20181125_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='city_code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditions',
            name='humidity',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
