# Generated by Django 2.0.3 on 2018-12-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='date_sun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('rise', models.CharField(max_length=100)),
                ('set', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='visible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('vis', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='date',
        ),
        migrations.RenameField(
            model_name='conditions',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='city_code',
        ),
        migrations.AddField(
            model_name='conditions',
            name='month',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
